services:
  queue_app:
    build:
      context: ./queue
      dockerfile: Dockerfile
    container_name: rmq_app_queue
    volumes:
      - ./config:/config
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      PORT: 3000
      NODE_ENV: production
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_ENDPOINT: ${RABBITMQ_ENDPOINT}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - app_network
    restart: unless-stopped

  queue_app_ssr:
    build:
      context: ./queue/client
      dockerfile: Dockerfile
      target: frontend-ssr-runtime
    container_name: rmq_app_queue_ssr
    environment:
      PORT: 9010
      NODE_ENV: production
      PROD: true
      API_BASE_URL: http://rmq_app_queue:3000
    expose:
      - 9010
    ports:
      - 9010:9010
    depends_on:
      queue_app:
        condition: service_started
    networks:
      - app_network
    restart: unless-stopped

  mysql:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}_mysql # nombre de referencia del servicio
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - 33062:3306
    volumes:
      - ./.volumes/mysql:/var/lib/mysql # carpeta local:carpeta de config de mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ${PROJECT_NAME}_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./.volumes/rabbitmq/data/:/var/lib/rabbitmq/
        - ./.volumes/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - app_network
    healthcheck:
      test: rabbitmq-diagnostics ping
      interval: 60s
      timeout: 5s
      retries: 2
      start_period: 30s
      start_interval: 10s
    restart: unless-stopped

networks:
  app_network:
    name: ${PROJECT_NAME}_network
    driver: bridge