services:
  app:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_app
    volumes:
      - ./config:/config
    environment:
      PROJECT_NAME: "${PROJECT_NAME}"
      PORT: 3001
      NODE_ENV: development
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_ENDPOINT: ${RABBITMQ_ENDPOINT}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      HUBSPOT_TOKEN: ${HUBSPOT_TOKEN}
      HUBSPOT_CLIENT_SECRET: ${HUBSPOT_CLIENT_SECRET}
    expose:
      - 3001
    ports:
      - 3001:3001
    networks:
      - app_network

networks:
  app_network:
    name: ${PROJECT_NAME}_network
    driver: bridge
